### ISSUE TITLE
Allow configuring REACT_APP_API_SUBSCRIPTION_URL to be relative path

### ISSUE THREAD

**Issue by gobengo** [erxes/erxes#1152]
I'm trying to make a configuration for deploying erxes, but I'd like this configuration to be agnostic as to what the finally-deployed hostname will be (e.g. erxes.example.com).

To enable this, I'd like to be able to configure `REACT_APP_API_SUBSCRIPTION_URL` environment variable to be a relative URL, not an absolute one.

e.g.
REACT_APP_API_SUBSCRIPTION_URL=/subscriptions-api

However, if I try this now, I get the following error when loading erxes.
```
Uncaught DOMException: Failed to construct 'WebSocket': The URL '/subscriptions-api' is invalid.
```

I believe this is because somewhere in apollo's subscriptions-transport-ws, it tries to do the equivalent of `new WebSocket('/subscriptions-api')`, but the WebSocket constructor requires being passed an absolute URI.

However, it's relatively trivial to create an absolute websocket URI from a relative path. https://stackoverflow.com/questions/10406930/how-to-construct-a-websocket-uri-relative-to-the-page-uri

Note, if you added this it might be easier to make the erxes [installation instructions for docker](https://docs.erxes.io/docs/installation/docker#docker-composeyml-file) more generic and not have to have the "Note: Following ENVs are configured for localhost only." (because we could move toward allowing non-absolute URLs in those environment variables).

Note: An alternative way of helping unblock me here would be to let me provide some JS as an environment variable (or mounted file in the container) that is inserted before the rest of the erxes JS. With that, I could insert some JS that builds a fully absolute URL and assigns it to window.REACT_APP_API_SUBSCRIPTION_URL.

Hope this makes sense. Let me know if it doesn't. Thanks!

**Comment by gobengo** [comment]
Update: I'd also like to be able to do the same for `REACT_APP_API_URL`. Setting it to an empty string or `.` doesn't work. As with the subscriptions url, I think a small amount of code around [where it's used in creating the apollo link](https://github.com/erxes/erxes/blob/c25f551c7ab616d4754af5fe4caac428d7e897b7/src/apolloClient.ts#L29) could make it work pretty well with relative paths.

**Comment by shinebayar-g** [comment]
Hi @gobengo . I guess you're trying to deploy erxes (backend) on suburl / subpath? (whatever you prefer to call it) I've setup like this on our demo instance.

```
erxes - erxes.example.com
erxes api - erxes.example.com/api
erxes widgets - erxes.example.com/widgets
erxes widgets api - erxes.example.com/widgets-api
erxes integrations - erxes.example.com/integrations
```
These are public facing processes and you can setup any reverse proxy you prefer. Here is example nginx, docker-compose config.

```nginx
server {
        listen 80;
        server_name erxes.example.com;
        index index.html;

        location / {
                proxy_pass http://127.0.0.1:3000/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /widgets-api/ {
                proxy_pass http://127.0.0.1:3100/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /widgets/ {
                proxy_pass http://127.0.0.1:3200/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/ {
                proxy_pass http://127.0.0.1:3300/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }

        location /integrations/ {
                proxy_pass http://127.0.0.1:3400/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}
```

```yml
version: "2.1"
services:
  erxes:
    image: erxes/erxes:0.9.17
    container_name: erxes
    restart: unless-stopped
    environment:
      # erxes
      REACT_APP_CDN_HOST: http://erxes.example.com/widgets
      REACT_APP_CDN_HOST_API: http://erxes.example.com/widgets-api
      REACT_APP_API_URL: http://erxes.example.com/api
      REACT_APP_API_SUBSCRIPTION_URL: ws://erxes.example.com/api/subscriptions
      REACT_APP_INTEGRATIONS_API_URL: http://erxes.example.com/integrations
      NGINX_HOST: erxes.example.com
    ports:
      - "3000:80"
    depends_on:
      erxes-api:
        condition: service_started
    networks:
      - erxes-net

  erxes-api:
    image: erxes/erxes-api:0.9.17
    container_name: erxes-api
    restart: unless-stopped
    environment:
      # erxes-api
      PORT: "3300"
      NODE_ENV: production
      HTTPS: "false"
      PUBSUB_TYPE: REDIS
      DEBUG: "erxes-api:*"
      # public urls
      DOMAIN: http://erxes.example.com/api
      MAIN_APP_DOMAIN: http://localhost:3000
      WIDGETS_DOMAIN: http://erxes.example.com/widgets
      INTEGRATIONS_API_DOMAIN: http://erxes.example.com/integrations
      # non public urls
      WIDGETS_API_DOMAIN: http://erxes-widgets-api:3100
      CRONS_API_DOMAIN: http://erxes-crons:3600
      WORKERS_API_DOMAIN: http://erxes-workers:3700
      LOGS_API_DOMAIN: http://erxes-logger:3800
      # MongoDB
      MONGO_URL: mongodb://mongo/erxes
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
    ports:
      - "3300:3300"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - erxes-net

  erxes-crons:
    image: erxes/erxes-api:0.9.17
    container_name: erxes-crons
    entrypoint: ["node", "--max_old_space_size=8192", "dist/cronJobs"]
    restart: unless-stopped
    environment:
      # erxes-crons
      PORT_CRONS: "3600"
      NODE_ENV: production
      PROCESS_NAME: crons
      DEBUG: "erxes-crons:*"
      # MongoDB
      MONGO_URL: mongodb://mongo/erxes
    ports:
      - "3600:3600"
    depends_on:
      mongo:
        condition: service_healthy
      erxes-api:
        condition: service_started
    networks:
      - erxes-net

  erxes-workers:
    image: erxes/erxes-api:0.9.17
    container_name: erxes-workers
    entrypoint: ["node", "--max_old_space_size=8192", "--experimental-worker", "dist/workers"]
    restart: unless-stopped
    environment:
      # erxes-workers
      PORT_WORKERS: "3700"
      NODE_ENV: production
      DEBUG: "erxes-workers:*"
      # MongoDB
      MONGO_URL: mongodb://mongo/erxes
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
    ports:
      - "127.0.0.1:3700:3700"
    depends_on:
      redis:
        condition: service_started
      mongo:
        condition: service_healthy
      erxes-api:
        condition: service_started
    networks:
      - erxes-net

  erxes-widgets:
    image: erxes/erxes-widgets:0.9.17
    container_name: erxes-widgets
    restart: unless-stopped
    environment:
      # erxes-widgets
      PORT: "3200"
      ROOT_URL: http://erxes.example.com/widgets
      MAIN_API_URL: http://erxes.example.com/api
      API_GRAPHQL_URL: http://erxes.example.com/widgets-api/graphql
      API_SUBSCRIPTIONS_URL: ws://erxes.example.com/api/subscriptions
    ports:
      - "3200:3200"
    depends_on:
      erxes-api:
        condition: service_started
    networks:
      - erxes-net

  erxes-widgets-api:
    image: erxes/erxes-widgets-api:0.9.17
    container_name: erxes-widgets-api
    restart: unless-stopped
    environment:
      # erxes-widgets-api
      PORT: "3100"
      NODE_ENV: production
      PUBSUB_TYPE: REDIS
      WIDGET_URL: http://erxes.example.com/widgets
      # MongoDB
      MONGO_URL: mongodb://mongo/erxes
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
    ports:
      - "3100:3100"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
      erxes-api:
        condition: service_started
    networks:
      - erxes-net

  erxes-integrations:
    image: erxes/erxes-integrations:0.9.17
    container_name: erxes-integrations
    restart: unless-stopped
    environment:
      PORT: "3400"
      NODE_ENV: production
      DEBUG: "erxes-integrations:*"
      # public urls
      DOMAIN: http://erxes.example.com/integrations
      MAIN_APP_DOMAIN: http://erxes.example.com
      MAIN_API_DOMAIN: http://erxes.example.com/api
      # non public urls
      # MongoDB
      MONGO_URL: mongodb://mongo/erxes_integrations
    ports:
      - "127.0.0.1:3400:3400"
    depends_on:
      mongo:
        condition: service_healthy
      erxes-api:
        condition: service_started
    networks:
      - erxes-net

  erxes-logger:
    image: erxes/erxes-logger:0.9.17
    container_name: erxes-logger
    restart: unless-stopped
    environment:
      PORT: "3800"
      DEBUG: "erxes-logs:*"
      # MongoDB
      MONGO_URL: mongodb://mongo/erxes_logs
    ports:
      - "127.0.0.1:3800:3800"
    depends_on:
      mongo:
        condition: service_healthy
      erxes-api:
        condition: service_started
    networks:
      - erxes-net

  redis:
    image: redis:5.0.5
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - erxes-net
    # Redis data will be saved into ./redisdata folder.
    volumes:
      - ./redisdata:/data

  mongo:
    image: mongo:3.6.13
    container_name: mongo
    restart: unless-stopped
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
      # start_period: 10s
    ports:
      - "27017:27017"
    networks:
      - erxes-net
    # MongoDB data will be saved into ./mongodata folder.
    volumes:
      - ./mongodata:/data/db

networks:
  erxes-net:
    driver: bridge
```
