### ISSUE TITLE
ERROR: for erxes-integrations  Container is unhealthy

### ISSUE THREAD

**Issue by solancer** [erxes/erxes#1211]
linuxsavvy:erxes srinivas$ docker-compose up -d
Creating network "erxes_erxes-net" with driver "bridge"
Creating rabbitmq ... done
Creating mongo    ... done
Creating redis    ... done

ERROR: for erxes-integrations  Container "815f936679a8" is unhealthy.

ERROR: for erxes-api  Container "815f936679a8" is unhealthy.

ERROR: for erxes-workers  Container "815f936679a8" is unhealthy.

ERROR: for erxes-crons  Container "815f936679a8" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by shinebayar-g** [comment]
What's the error outputs, logs of those containers?

**Comment by shinebayar-g** [comment]
I've updated to docker installation [docs](https://docs.erxes.io/docs/installation/docker) to latest release and revised services' healthchecks. Optimized potential unhealthy conditions when `retries` is set too low.

**Comment by karser** [comment]
In my case the rabbitmq container didn't go to healthy state unless I increased timeout and interval up to 5s:
```
    rabbitmq:
        image: rabbitmq:3.7.17-management
        healthcheck:
            timeout: 5s
            interval: 5s
            retries: 5
            test:
                - "CMD"
                - "rabbitmqctl"
                - "status"
```
