### ISSUE TITLE
How to install/deploy on remote

### ISSUE THREAD

**Issue by denisdemolli** [erxes/erxes#1555]
Hi all, this project looks great. I appreciate your work and I would like to learn more about it, but I have a problem with installation on a remote machine (digital ocean). I read the docs on the web and issues here on GitHub but wasn't able to solve it. I am using just an IP address, not a domain name. I tried both docker and ubuntu installation. Not working for me. I guess some configuration is wrong on my part. I would appreciate any advice. With Docker, I have a problem with the erxes-api container. It exited after a few seconds. With ubuntu installation, I don't have errors in the terminal, but in browser, I got 500 internal error. I would really appreciate it if someone points me in the right direction. This is the configuration I tried so far.

DOCKER Installation (erxes version: 0.11.2):
nginx ( in /etc/nginx/sites-available/default):
```
server {
    server_name 142.93.109.147;
    listen 80;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /widgets-api/ {
        proxy_pass http://127.0.0.1:3100/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /widgets/ {
        proxy_pass http://127.0.0.1:3200/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3300/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

```yaml
docker-compose:
version: "3"
services:
  erxes:
    image: erxes/erxes:0.11.2
    container_name: erxes
    environment:
      REACT_APP_CDN_HOST: http://142.93.109.147/widgets
      REACT_APP_CDN_HOST_API: http://142.93.109.147/widgets-api
      REACT_APP_API_URL: http://142.93.109.147/api
      REACT_APP_API_SUBSCRIPTION_URL: ws://142.93.109.147/api/subscriptions
      NGINX_HOST: 142.93.109.147
    ports:
      - "127.0.0.1:3000:80"
    networks:
      - erxes-net

  erxes-widgets-api:
    image: erxes/erxes-widgets-api:0.11.2
    container_name: erxes-widgets-api
    environment:
      NODE_ENV: production
      WIDGET_URL: http://142.93.109.147/widgets
      MAIN_API_URL: http://142.93.109.147/api/graphql
      MONGO_URL: mongodb://mongo/erxes
    ports:
      - "127.0.0.1:3100:3100"
    depends_on:
      - mongo
    networks:
      - erxes-net

  erxes-api:
    image: erxes/erxes-api:0.11.2
    container_name: erxes-api
    environment:
      REDIS_HOST: redis
      NODE_ENV: production
      MONGO_URL: mongodb://mongo/erxes
      USE_REPLICATION: "false"
      HTTPS: "false"
      WIDGETS_DOMAIN: http://142.93.109.147/widgets
      MAIN_APP_DOMAIN: http://142.93.109.147
      DOMAIN: http://142.93.109.147/api
    ports:
      - "127.0.0.1:3300:3300"
    depends_on:
      - mongo
      - redis
    networks:
      - erxes-net

  erxes-widgets:
    image: erxes/erxes-widgets:0.11.2
    container_name: erxes-widgets
    environment:
      MAIN_API_URL: http://142.93.109.147/api
      API_SUBSCRIPTIONS_URL: ws://142.93.109.147/api/subscriptions
      API_GRAPHQL_URL: http://142.93.109.147/widgets-api/graphql
      ROOT_URL: http://142.93.109.147/widgets
    ports:
      - "127.0.0.1:3200:3200"
    networks:
      - erxes-net

  redis:
    image: redis:4-alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - erxes-net
    # Redis data will be saved into ./redisdata folder.
    volumes:
      - ./redisdata:/data

  mongo:
    image: mongo:3.6
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - erxes-net
    # MongoDB data will be saved into ./mongodata folder.
    volumes:
      - ./mongodata:/data/db

networks:
  erxes-net:
    driver: bridge

```

UBUNTU installation (erxes version: 0.11.2)
nginx ( in /etc/nginx/sites-available/default):
```
server {
        listen 80;
        server_name 142.93.109.147;
        # Don't forget to update below path with /path/to/erxes/build;
        root /home/erxes.io/erxes/build;
        index index.html;
        error_log /var/log/nginx/erxes.error.log;

        location / {
                try_files $uri /index.html;
        }

        # Assumming widgets-api project is running on 3100 port.
        location /widgets-api/ {
                proxy_pass http://127.0.0.1:3100/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Assumming widgets project is running on 3200 port.
        location /widgets/ {
                proxy_pass http://127.0.0.1:3200/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Assumming api project is running on 3300 port.
        location /api/ {
                proxy_pass http://127.0.0.1:3300/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }
}
```
```env
.env files:
ERXES:
PORT=3000
NODE_ENV=production
REACT_APP_CDN_HOST=http://142.93.109.147:3200
REACT_APP_CDN_HOST_API=http://142.93.109.147:3100
REACT_APP_API_URL=http://142.93.109.147:3300
REACT_APP_API_SUBSCRIPTION_URL=ws://142.93.109.147:3300/subscriptions

ERXES-API:
PORT=3300
NODE_ENV=production
HTTPS=false
PUBSUB_TYPE='REDIS'
UPLOAD_SERVICE_TYPE='AWS'
FILE_SYSTEM_PUBLIC='false'
DOMAIN=http://142.93.109.147:3300
MAIN_APP_DOMAIN=http://142.93.109.147:3000
WIDGETS_DOMAIN=http://142.93.109.147:3200
INTEGRATIONS_API_DOMAIN=http://142.93.109.147:3400
WIDGETS_API_DOMAIN=http://142.93.109.147:3100
CRONS_API_DOMAIN=
WORKERS_API_DOMAIN=
LOGS_API_DOMAIN=
ENGAGES_API_DOMAIN=
MONGO_URL=mongodb://localhost/erxes
TEST_MONGO_URL=mongodb://localhost/test
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=
RABBITMQ_HOST=amqp://142.93.109.147
COMPANY_EMAIL_FROM=noreply@erxes.io
DEFAULT_EMAIL_SERVICE=sendgrid
MAIL_SERVICE=sendgrid
MAIL_PORT=''
MAIL_USER=''
MAIL_PASS=''
MAIL_HOST=''
AWS_ACCESS_KEY_ID=''
AWS_SECRET_ACCESS_KEY=''
AWS_BUCKET=''
AWS_PREFIX=''
AWS_COMPATIBLE_SERVICE_ENDPOINT=''
AWS_FORCE_PATH_STYLE=false
AWS_SES_ACCESS_KEY_ID=''
AWS_SES_SECRET_ACCESS_KEY=''
AWS_REGION=''
AWS_SES_CONFIG_SET=erxes
GOOGLE_CLIENT_ID=''
GOOGLE_CLIENT_SECRET=''
GOOGLE_APPLICATION_CREDENTIALS=''
GOOGLE_TOPIC=''
GOOGLE_SUBSCRIPTION_NAME=''
GOOGLE_PROJECT_ID=''
GOOGLE_CLOUD_STORAGE_BUCKET=''
PORT_CRONS=3600
PORT_WORKERS=3700
USE_BRAND_RESTRICTIONS=false
UPLOAD_FILE_TYPES=image/png,image/jpeg,image/jpg,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/pdf,

ERXES-WIDGETS:
PORT=3200
ROOT_URL=http://142.93.109.147:3200
MAIN_API_URL=http://142.93.109.147:3300
API_GRAPHQL_URL=http://142.93.109.147:3100/graphql
API_SUBSCRIPTIONS_URL=ws://142.93.109.147:3300/subscriptions

ERXES-WIDGETS-API:
PORT=3100
NODE_ENV=production
WIDGET_URL=http://142.93.109.147:3200
MONGO_URL=mongodb://localhost/erxes
TEST_MONGO_URL=mongodb://localhost/erxesApiTest
RABBITMQ_HOST=amqp://142.93.109.147

```

**Comment by Jason-2020** [comment]
Hi similar issue reported recently and I'd like to investigate on this issue and will get back to you asap.

I assume our documentation isn't perfect enough to get going with minimal effort.

**Comment by denisdemolli** [comment]
Hi, I tried different configurations and was able to run it eventually. I add my config if anyone has similar issue. But I wonder why I can't see the popUp feature?

![erxesNoPopUps](https://user-images.githubusercontent.com/23063636/72019611-5740ad00-326a-11ea-8104-ed4e1928c4bc.png)

docker-compose.yml:
```
version: "3"
services:
  erxes:
    image: erxes/erxes:develop-latest
    container_name: erxes
    environment:
      REACT_APP_CDN_HOST: http://mydomain.com/widgets
      REACT_APP_CDN_HOST_API: http://mydomain.com/widgets-api
      REACT_APP_API_URL: http://mydomain.com/api
      REACT_APP_API_SUBSCRIPTION_URL: ws://mydomain.com/api/subscriptions
      NGINX_HOST: mydomain.com
    ports:
      - "127.0.0.1:3000:80"
    networks:
      - erxes-net

  erxes-widgets-api:
    image: erxes/erxes-widgets-api:develop-latest
    container_name: erxes-widgets-api
    environment:
      NODE_ENV: production
      WIDGET_URL: http://mydomain.com/widgets
      MAIN_API_URL: http://mydomain.com/api/graphql
      MONGO_URL: mongodb://mongo/erxes
    ports:
      - "127.0.0.1:3100:3100"
    depends_on:
      - mongo
    networks:
      - erxes-net

  erxes-api:
    image: erxes/erxes-api:develop-latest
    container_name: erxes-api
    environment:
      REDIS_HOST: redis
      NODE_ENV: production
      MONGO_URL: mongodb://mongo/erxes
      USE_REPLICATION: "false"
      HTTPS: "false"
      WIDGETS_DOMAIN: http://mydomain.com/widgets
      MAIN_APP_DOMAIN: http://mydomain.com
      DOMAIN: http://mydomain.com/api
    ports:
      - "127.0.0.1:3300:3300"
    depends_on:
      - mongo
      - redis
    networks:
      - erxes-net

  erxes-widgets:
    image: erxes/erxes-widgets:develop-latest
    container_name: erxes-widgets
    environment:
      MAIN_API_URL: http://mydomain.com/api
      API_SUBSCRIPTIONS_URL: ws://mydomain.com/api/subscriptions
      API_GRAPHQL_URL: http://mydomain.com/widgets-api/graphql
      ROOT_URL: http://mydomain.com/widgets
    ports:
      - "127.0.0.1:3200:3200"
    networks:
      - erxes-net

  redis:
    image: redis:4-alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - erxes-net
    # Redis data will be saved into ./redisdata folder.
    volumes:
      - ./redisdata:/data

  mongo:
    image: mongo:3.6
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - erxes-net
    # MongoDB data will be saved into ./mongodata folder.
    volumes:
      - ./mongodata:/data/db

networks:
  erxes-net:
    driver: bridge
```

nginx:

```
server {
    server_name mydomain.com;
    listen 80;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /widgets-api/ {
        proxy_pass http://127.0.0.1:3100/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /widgets/ {
        proxy_pass http://127.0.0.1:3200/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3300/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```
