### ISSUE TITLE
elksyncer in docker fails to talk to mongo if in separate container (docker)

### ISSUE THREAD

**Issue by ned-kelly** [erxes/erxes#2593]
When running elksyncer in a docker environment the container will fail to connect to mongo as it's running on a different host (even if `MONGO_URL` and `ELASTICSEARCH_URL` are set...)

(see here: https://github.com/erxes/erxes/blob/master/elkSyncer/main.py#L186)

According to [MongoConnector documentation](https://github.com/yougov/mongo-connector/wiki/Configuration-Options#mainaddress), we need to add the `-m` flag like: `-m mongo-container:27017`.

I propose adding an additional environment variable which can be added to add this flag if it's set if the sysadmin is running erxes on a docker deployment.

----

For now (should anyone want to get the latest elksyncer running on 0.20.X) I suggest the following docker compose setup:

### 1. Create an executable `elksyncer-fix.sh` script with the following:

```sh
#!/bin/sh

apk update && apk add socat
socat TCP-LISTEN:27017,fork TCP:mongo:27017 &

python main.py
```

### 2. Use the following snippet in your [docker-compose file](https://github.com/erxes/erxes/issues/2449#issuecomment-722767148)...

```yaml
  erxes-elksyncer:
    container_name: "erxes-elksyncer"
    image: erxes/erxes-elksyncer:0.20.10
    restart: always

    environment:
      MONGO_URL: mongodb://mongo/erxes
      ELASTICSEARCH_URL: http://elasticsearch:9200

    depends_on:
      mongo:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - erxes-net

    volumes:
      - ./elksyncer-fix.sh:/elkSyncer/elksyncer-fix.sh

    # overwrite default image entrypoint to forward mongo port to mongo container...
    entrypoint: ["sh", "/elkSyncer/elksyncer-fix.sh"]
```
