### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by warproxxx** [erxes/erxes#810]
I am getting a CORS issue and am unable to login.

I followed the steps and created this yaml file:

```YAML
version: "3"
services:
  erxes:
    image: erxes/erxes:docker-latest
    container_name: erxes
    environment:
      REACT_APP_CDN_HOST: http://io.getsaasy.co:3200
      REACT_APP_CDN_HOST_API: http://io.getsaasy.co:3100
      REACT_APP_API_URL: http://io.getsaasy.co:3300
      REACT_APP_API_SUBSCRIPTION_URL: ws://io.getsaasy.co:3300/subscriptions
      NGINX_HOST: io.getsaasy.co
    ports:
      - "3000:80"
    networks:
      - erxes-net

  erxes-widgets-api:
    image: erxes/erxes-widgets-api:develop-latest
    container_name: erxes-widgets-api
    environment:
      NODE_ENV: production
      WIDGET_URL: http://io.getsaasy.co:3200
      MAIN_API_URL: http://io.getsaasy.co:3300/graphql
      MONGO_URL: mongodb://mongo/erxes
    ports:
      - "3100:3100"
    depends_on:
      - mongo
    networks:
      - erxes-net

  erxes-api:
    image: erxes/erxes-api:develop-latest
    container_name: erxes-api
    environment:
      REDIS_HOST: redis
      NODE_ENV: production
      MONGO_URL: mongodb://mongo/erxes
      USE_REPLICATION: "false"
      HTTPS: "false"
      WIDGETS_DOMAIN: http://io.getsaasy.co:3200
      MAIN_APP_DOMAIN: http://io.getsaasy.co:3000
      DOMAIN: http://io.getsaasy.co:3300
    ports:
      - "3300:3300"
    depends_on:
      - mongo
      - redis
    networks:
      - erxes-net

  erxes-widgets:
    image: erxes/erxes-widgets:develop-latest
    container_name: erxes-widgets
    environment:
      MAIN_API_URL: http://io.getsaasy.co:3300
      API_SUBSCRIPTIONS_URL: ws://io.getsaasy.co:3300/subscriptions
      API_GRAPHQL_URL: http://io.getsaasy.co:3100/graphql
      ROOT_URL: http://io.getsaasy.co:3200
    ports:
      - "3200:3200"
    networks:
      - erxes-net

  redis:
    image: redis:4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - erxes-net
    # Redis data will be saved into ./redisdata folder.
    volumes:
      - ./redisdata:/data

  mongo:
    image: mongo:3.6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - erxes-net
    # MongoDB data will be saved into ./mongodata folder.
    volumes:
      - ./mongodata:/data/db

networks:
  erxes-net:
    driver: bridge

```

Then my nginx config looks like this

```Nginx
server {
    server_name io.getsaasy.co;
    listen 80;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /widgets-api/ {
        proxy_pass http://127.0.0.1:3100/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /widgets/ {
        proxy_pass http://127.0.0.1:3200/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3300/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

All my containers are running well however i am getting this issue:
https://i.imgur.com/gxTgsGF.png

**Comment by shinebayar-g** [comment]
Hello, first of all thanks for trying out our app!

Reason why you're getting CORS is because it's not configured correctly. Your nginx configuration is correct. However your docker-compose.yml is not quite right.
If you take a look at nginx configuration you'd notice it's doing something like this:

erxes-api (running on port 3300) -> nginx (listening on io.getsaasy.co & forwards io.getsaasy.co/api/ request to something listening on port 3300). So end users will access **erxes-api** service by browsing `http://io.getsaasy.co/api/` endpoint. _Note_: It's not `http://io.getsaasy.co:3300`. At this point you'd notice what's missing here right?

Your docker-compose.yml file should look like this:

```YAML
version: "3"
services:
  erxes:
    image: erxes/erxes:docker-latest
    container_name: erxes
    environment:
      REACT_APP_CDN_HOST: http://io.getsaasy.co/widgets
      REACT_APP_CDN_HOST_API: http://io.getsaasy.co/widgets-api
      REACT_APP_API_URL: http://io.getsaasy.co/api
      REACT_APP_API_SUBSCRIPTION_URL: ws://io.getsaasy.co/api/subscriptions
      NGINX_HOST: io.getsaasy.co
    ports:
      - "127.0.0.1:3000:80"
    networks:
      - erxes-net

  erxes-widgets-api:
    image: erxes/erxes-widgets-api:develop-latest
    container_name: erxes-widgets-api
    environment:
      NODE_ENV: production
      WIDGET_URL: http://io.getsaasy.co/widgets
      MAIN_API_URL: http://io.getsaasy.co/api/graphql
      MONGO_URL: mongodb://mongo/erxes
    ports:
      - "127.0.0.1:3100:3100"
    depends_on:
      - mongo
    networks:
      - erxes-net

  erxes-api:
    image: erxes/erxes-api:develop-latest
    container_name: erxes-api
    environment:
      REDIS_HOST: redis
      NODE_ENV: production
      MONGO_URL: mongodb://mongo/erxes
      USE_REPLICATION: "false"
      HTTPS: "false"
      WIDGETS_DOMAIN: http://io.getsaasy.co/widgets
      MAIN_APP_DOMAIN: http://io.getsaasy.co
      DOMAIN: http://io.getsaasy.co/api
    ports:
      - "127.0.0.1:3300:3300"
    depends_on:
      - mongo
      - redis
    networks:
      - erxes-net

  erxes-widgets:
    image: erxes/erxes-widgets:develop-latest
    container_name: erxes-widgets
    environment:
      MAIN_API_URL: http://io.getsaasy.co/api
      API_SUBSCRIPTIONS_URL: ws://io.getsaasy.co/api/subscriptions
      API_GRAPHQL_URL: http://io.getsaasy.co/widgets-api/graphql
      ROOT_URL: http://io.getsaasy.co/widgets
    ports:
      - "127.0.0.1:3200:3200"
    networks:
      - erxes-net

  redis:
    image: redis:4-alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - erxes-net
    # Redis data will be saved into ./redisdata folder.
    volumes:
      - ./redisdata:/data

  mongo:
    image: mongo:3.6
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - erxes-net
    # MongoDB data will be saved into ./mongodata folder.
    volumes:
      - ./mongodata:/data/db

networks:
  erxes-net:
    driver: bridge
```

I've changed all of your environment variables to correct one. Also I've changed all docker container's listening port to 127.0.0.1. Because if you just put 3300:3300 like this, it will listen on all network address of server (both public and private) I guess you wouldn't want this, since you're running nginx in front of applications.
