### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by manojkothari** [erxes/erxes#832]
![image](https://user-images.githubusercontent.com/38829597/53800922-e0f55f00-3f63-11e9-90a7-be0c649bcaea.png)

I tried to install as per the document...  No error occured and I was able to see the UI on 3000 port but once I tried login with admin@erxes.io account I am getting error. See attached screenshot for details..

**Comment by shinebayar-g** [comment]
Hi, I have a few questions to understand what's going on there.
1. Did you install erxes on your local computer or remote computer? If it's on remote computer did you setup your domain and nginx as well?
2. Did you use docker or just cloned all repo?

**Comment by manojkothari** [comment]
I used docker and installed on Google Cloud

**Comment by manojkothari** [comment]
I followed this link https://github.com/erxes/erxes/wiki/Use-erxes-with-Docker

**Comment by shinebayar-g** [comment]
I see thank you. Did you install nginx and setup your domain?
If you open up your browser's developer console, there will be bunch of errors. Please take screenshots of them.

Make sure you installed nginx and setup your domain, and also configure erxes env settings in your `docker-compose.yml` file. Your docker compose file should look like this:

```YAML
version: "3"
services:
  erxes:
    image: erxes/erxes:develop-latest
    container_name: erxes
    environment:
      REACT_APP_CDN_HOST: http://erxes.yourdomain.com/widgets
      REACT_APP_CDN_HOST_API: http://erxes.yourdomain.com/widgets-api
      REACT_APP_API_URL: http://erxes.yourdomain.com/api
      REACT_APP_API_SUBSCRIPTION_URL: ws://erxes.yourdomain.com/api/subscriptions
      NGINX_HOST: erxes.yourdomain.com
```
etc..
