### ISSUE TITLE
Docker: MongoDB Fails to launch on Windows

### ISSUE THREAD

**Issue by lazmo88** [erxes/erxes#890]
Hello, tried testing erxes on Win10 Pro machine running, but the MongoDB instance fails to launch.

Is this a known issue?

**Comment by shinebayar-g** [comment]
Hi @lazmo88 Are you familiar with MongoDB on Windows? I mean did you follow their [installation instruction](https://docs.mongodb.com/v3.6/tutorial/install-mongodb-on-windows/) on windows? Roughly speaking _MongoDB fails to launch_ has nothing to do with erxes.

Do you have any logs or error messages? Afaik, MongoDB will not start on Windows, until it properly configured.

**Comment by lazmo88** [comment]
@shinebayar-g Perhaps I was not clear enough, my apologies. The official docker-compose.yml file includes the MongoDB container instance that is supposed to be automatically launched when running docker-compose up -d - all other containers launches, but MongoDB fails on start. Therefore I was wondering if someone else has had the same issue running the official docker images on Windows.

**Comment by shinebayar-g** [comment]
@lazmo88 Ah I see, so you're using docker on Windows? I thought you just cloned all repo and installed manually, sorry.

Did you use [this](https://github.com/erxes/erxes/wiki/Use-erxes-with-Docker) instructions to setup erxes?

I believe you can check out docker logs. What's the output of `docker ps` and `docker ps -a` after you run `docker-compose up -d` in folder you saved `docker-compose.yml` file ?

If MongoDB container has exited, you can check its logs with `docker logs <container_name_here> `command e.g: `docker logs mongo`

There should be logs explaining what's going wrong there unless you remove exited containers.

**Comment by lazmo88** [comment]
@shinebayar-g Yes running Docker on windows :) Here is the container log for MongoDB.

`2019-04-22T08:00:37.428+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=bd3931a6fe4a,
2019-04-22T08:00:37.428+0000 I CONTROL  [initandlisten] db version v3.6.12,
2019-04-22T08:00:37.428+0000 I CONTROL  [initandlisten] git version: c2b9acad0248ca06b14ef1640734b5d0595b55f1,
2019-04-22T08:00:37.428+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016,
2019-04-22T08:00:37.428+0000 I CONTROL  [initandlisten] allocator: tcmalloc,
2019-04-22T08:00:37.428+0000 I CONTROL  [initandlisten] modules: none,
2019-04-22T08:00:37.428+0000 I CONTROL  [initandlisten] build environment:,
2019-04-22T08:00:37.428+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604,
2019-04-22T08:00:37.428+0000 I CONTROL  [initandlisten]     distarch: x86_64,
2019-04-22T08:00:37.428+0000 I CONTROL  [initandlisten]     target_arch: x86_64,
2019-04-22T08:00:37.428+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } },
2019-04-22T08:00:37.431+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=478M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),,
2019-04-22T08:00:38.027+0000 E STORAGE  [initandlisten] WiredTiger error (17) [1555920038:27320][1:0x7fa4db0dda40], connection: __posix_open_file, 715: /data/db/WiredTiger.wt: handle-open: open: File exists,
2019-04-22T08:00:38.029+0000 I STORAGE  [initandlisten] WiredTiger message unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.4,
2019-04-22T08:00:38.030+0000 E STORAGE  [initandlisten] WiredTiger error (1) [1555920038:30786][1:0x7fa4db0dda40], connection: __posix_open_file, 715: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted,
2019-04-22T08:00:38.032+0000 E -        [initandlisten] Assertion: 28595:1: Operation not permitted src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 486,
2019-04-22T08:00:38.032+0000 I STORAGE  [initandlisten] exception in initAndListen: Location28595: 1: Operation not permitted, terminating,
2019-04-22T08:00:38.032+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...,
2019-04-22T08:00:38.032+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock,
2019-04-22T08:00:38.032+0000 I CONTROL  [initandlisten] now exiting,
2019-04-22T08:00:38.032+0000 I CONTROL  [initandlisten] shutting down with code:100,`

**Comment by shinebayar-g** [comment]
Okay, not sure what this means. 

```
2019-04-22T08:00:38.027+0000 E STORAGE  [initandlisten] WiredTiger error (17) [1555920038:27320][1:0x7fa4db0dda40], connection: __posix_open_file, 715: /data/db/WiredTiger.wt: handle-open: open: File exists,
```

You can try to start mongodb without volume. I think it'll work.
```yaml
  mongo:
    image: mongo:3.6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - erxes-net
    # MongoDB data will be saved into ./mongodata folder.
    # volumes:
    #  - ./mongodata:/data/db
```

Does docker actually creating folder named `mongodata` in your docker-compose folder?
If yes, try to delete that folder and restart again. If not or even if you delete this folder and restart, and problem still persists, I think `- ./mongodata:/data/db` this method is not working.
If that's the case you should modify your docker-compose.yml file like this:
```yaml
...
...
  mongo:
    image: mongo:3.6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - erxes-net
    # MongoDB data will be saved into ./mongodata folder.
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:

networks:
  erxes-net:
    driver: bridge
```

**Comment by lazmo88** [comment]
**Does docker actually creating folder named mongodata in your docker-compose folder?**

Yes, the folder is created, I tested the modifications and mongodb runs now, and I am able to create default admin/password for erxes instance via exres-api, but when I try to login via frontend it shows following toast warnings "Disconnect" and "Network error: Failed to fetch" and login requests are failed.

It is very strange as mongodb is running and exres does have a connection to it.

**Comment by lazmo88** [comment]
@shinebayar-g it seems that the problem is with the official docker images itself (https://github.com/erxes/erxes/wiki/Use-erxes-with-Docker).

We tried running the stack on Ubuntu machine and exactly same behavior with frontend  <> MongoDB instance connection issues are still ongoing. As said, weirdly enough the erxes-api container has full connection to mongodb and default admin user can be created.

**Comment by shinebayar-g** [comment]
@lazmo88 

> "Disconnect" and "Network error: Failed to fetch"

Looks like you didn't configure your env settings in your docker-compose.yml file.

For e.g
```yaml
  erxes:
    image: erxes/erxes:develop-latest
    container_name: erxes
    environment:
      REACT_APP_CDN_HOST: http://localhost:3200
      REACT_APP_CDN_HOST_API: http://localhost:3100
      REACT_APP_API_URL: http://localhost:3300
      REACT_APP_API_SUBSCRIPTION_URL: ws://localhost:3300/subscriptions
      NGINX_HOST: localhost
```

These are erxes frontend env settings. If you're running erxes on your localhost, default configuration will work. However if you're running it behind reverse proxy or exposing with direct IP these configurations should be modified. For reference please see https://github.com/erxes/erxes/issues/832 https://github.com/erxes/erxes/issues/765 https://github.com/erxes/erxes/issues/741
How to setup nginx https://github.com/erxes/erxes/wiki/Running-behind-Nginx
